version = "Two"
edition = "2021"
brace_style = "AlwaysNextLine"
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
# imports_indent = "Visual"
imports_layout = "HorizontalVertical"
imports_granularity = "Module"
max_width = 60
normalize_comments = true
normalize_doc_attributes = true
newline_style = "Unix"
reorder_impl_items = true
spaces_around_ranges = true
tab_spaces = 2
unstable_features = true
use_try_shorthand = true
wrap_comments = true
