[tasks.coverage]
workspace = false
alias = "llvm-cov"

[tasks.llvm-cov]
workspace = false
command = "cargo"
args = ["llvm-cov", "--ignore-filename-regex", "main|compiler/mod", "${@}"]

[tasks.test]
workspace = false
command = "cargo"
args = ["test", "${@}"]

[tasks.mabel-dev]
workspace = false
env = { RUSTFLAGS = "-Awarnings" }
command = "cargo"
args = ["run", "-q", "--", "${@}"]
