name: CI
on:
  push:
    branches:
      - main
env: 
  CARGO_TERM_COLOR: always
jobs:
  setup:
    name: Run tests and create coverage report
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update nightly && rustup default nightly
      - name: Install Cargo tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-make,cargo-llvm-cov
      - name: Run Tests
        run: cargo make test
      - name: Run Coverage
        run: cargo make coverage --lcov --output-path lcov.info
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          file: lcov.info
          name: lcov-${{ matrix.os }}.info
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
